# Generated by Django 4.2.7 on 2026-02-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_custom_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', help_text='User interface language preference', max_length=10),
        ),
    ]
