# Generated by Django 4.2.7 on 2026-02-25 16:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('nutritionist', 'Nutritionist'), ('receptionist', 'Receptionist'), ('branch_admin', 'Branch Admin'), ('super_admin', 'Super Admin')], max_length=20, verbose_name='role')),
                ('employee_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Only uppercase letters and numbers')], verbose_name='employee ID')),
                ('specialization', models.CharField(blank=True, help_text='e.g., Cardiology, Clinical Pharmacy, Sports Nutrition', max_length=100, verbose_name='specialization')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='license number')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='department/unit')),
                ('work_phone', models.CharField(blank=True, max_length=20, verbose_name='work phone')),
                ('work_email', models.EmailField(blank=True, max_length=254, verbose_name='work email')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('joined_date', models.DateField(verbose_name='joined date')),
                ('left_date', models.DateField(blank=True, null=True, verbose_name='left date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_patients', models.ManyToManyField(blank=True, related_name='assigned_staff', to='patients.patient', verbose_name='assigned patients')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='branches.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff members',
                'permissions': [('can_manage_staff', 'Can manage staff members'), ('can_assign_patients', 'Can assign patients to staff'), ('can_view_all_branches', 'Can view all branches data')],
                'indexes': [models.Index(fields=['branch', 'role'], name='staff_staff_branch__527fa8_idx'), models.Index(fields=['user', 'is_active'], name='staff_staff_user_id_5ba100_idx'), models.Index(fields=['employee_id'], name='staff_staff_employe_f8cd0b_idx')],
                'unique_together': {('user', 'branch'), ('branch', 'employee_id')},
            },
        ),
    ]
