# Generated by Django 4.2.7 on 2026-02-22 01:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Allowed file types: PDF, Word, Excel, images, text', upload_to=files.models.patient_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'tiff', 'txt', 'csv'])], verbose_name='file')),
                ('category', models.CharField(choices=[('lab_report', 'Lab Report'), ('xray', 'X-Ray / Radiology'), ('prescription', 'Prescription'), ('identification', 'Identification Document'), ('insurance', 'Insurance Document'), ('consent', 'Consent Form'), ('medical_history', 'Medical History'), ('other', 'Other')], default='other', max_length=50, verbose_name='category')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('file_size', models.PositiveIntegerField(editable=False, verbose_name='file size (bytes)')),
                ('content_type', models.CharField(editable=False, max_length=100, verbose_name='content type')),
                ('file_extension', models.CharField(editable=False, max_length=20, verbose_name='file extension')),
                ('checksum', models.CharField(editable=False, help_text='SHA-256 checksum for file integrity', max_length=64, verbose_name='checksum')),
                ('is_encrypted', models.BooleanField(default=False, editable=False, verbose_name='encrypted')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='download count')),
                ('last_accessed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='patients.patient', verbose_name='patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'medical file',
                'verbose_name_plural': 'medical files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'category'], name='files_medic_patient_a01ea0_idx'), models.Index(fields=['patient', '-created_at'], name='files_medic_patient_30c10a_idx'), models.Index(fields=['uploaded_by'], name='files_medic_uploade_43da41_idx'), models.Index(fields=['checksum'], name='files_medic_checksu_5e9d2a_idx')],
            },
        ),
    ]
