# Generated by Django 4.2.7 on 2026-02-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalfile',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum for file integrity', max_length=64, verbose_name='checksum'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='file_extension',
            field=models.CharField(blank=True, max_length=20, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='file size (bytes)'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='original filename'),
        ),
    ]
