# Generated by Django 4.2.7 on 2026-02-25 18:47

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='search name')),
                ('query', models.CharField(max_length=255, verbose_name='search query')),
                ('filters', models.JSONField(default=dict, verbose_name='filters')),
                ('notify_on_new', models.BooleanField(default=False, verbose_name='notify on new results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'saved search',
                'verbose_name_plural': 'saved searches',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255, verbose_name='search query')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filters')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='result count')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='searched at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'recent search',
                'verbose_name_plural': 'recent searches',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['user', '-searched_at'], name='search_rece_user_id_d0e849_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientSearchIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mrn', models.CharField(db_index=True, max_length=20, verbose_name='MRN')),
                ('national_id', models.CharField(db_index=True, max_length=20, verbose_name='national ID')),
                ('full_name', models.TextField(db_index=True, verbose_name='full name')),
                ('full_name_arabic', models.TextField(blank=True, verbose_name='full name (Arabic)')),
                ('phone_mobile', models.CharField(blank=True, max_length=20, verbose_name='mobile phone')),
                ('phone_home', models.CharField(blank=True, max_length=20, verbose_name='home phone')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email')),
                ('date_of_birth', models.DateField(db_index=True, verbose_name='date of birth')),
                ('branch_id', models.UUIDField(db_index=True, verbose_name='branch ID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='patients.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'patient search index',
                'verbose_name_plural': 'patient search indexes',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_pati_search__f293cc_gin'), models.Index(fields=['full_name'], name='search_pati_full_na_45ca4f_idx'), models.Index(fields=['mrn', 'branch_id'], name='search_pati_mrn_2ce134_idx'), models.Index(fields=['national_id', 'branch_id'], name='search_pati_nationa_2562c1_idx')],
            },
        ),
    ]
