# Generated by Django 4.2.7 on 2026-02-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsearchindex',
            name='branch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='branch ID'),
        ),
        migrations.AlterField(
            model_name='patientsearchindex',
            name='date_of_birth',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='patientsearchindex',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='patientsearchindex',
            name='full_name',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='patientsearchindex',
            name='full_name_arabic',
            field=models.TextField(blank=True, default='', verbose_name='full name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='patientsearchindex',
            name='mrn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='MRN'),
        ),
        migrations.AlterField(
            model_name='patientsearchindex',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='national ID'),
        ),
        migrations.AlterField(
            model_name='patientsearchindex',
            name='phone_home',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='home phone'),
        ),
        migrations.AlterField(
            model_name='patientsearchindex',
            name='phone_mobile',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='mobile phone'),
        ),
    ]
