# Generated by Django 4.2.7 on 2026-02-22 00:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0002_alter_branch_address_alter_branch_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id', models.CharField(help_text='National ID or Civil ID', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numbers allowed')], verbose_name='national ID')),
                ('mrn', models.CharField(help_text='Unique medical record number', max_length=20, unique=True, verbose_name='medical record number')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('mother_name', models.CharField(blank=True, help_text='Important for family relations', max_length=200, verbose_name="mother's name")),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('place_of_birth', models.CharField(blank=True, max_length=200, verbose_name='place of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, verbose_name='marital status')),
                ('nationality', models.CharField(default='Jordanian', max_length=100, verbose_name='nationality')),
                ('phone_mobile', models.CharField(max_length=20, verbose_name='mobile phone')),
                ('phone_home', models.CharField(blank=True, max_length=20, verbose_name='home phone')),
                ('phone_work', models.CharField(blank=True, max_length=20, verbose_name='work phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address_line1', models.CharField(max_length=255, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state/province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('country', models.CharField(default='Jordan', max_length=100, verbose_name='country')),
                ('emergency_contact_name', models.CharField(max_length=200, verbose_name='emergency contact name')),
                ('emergency_contact_relationship', models.CharField(max_length=100, verbose_name='relationship')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='emergency contact phone')),
                ('insurance_provider', models.CharField(blank=True, max_length=200, verbose_name='insurance provider')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, verbose_name='policy number')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True, verbose_name='insurance expiry date')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this patient is currently active.', verbose_name='active')),
                ('is_deceased', models.BooleanField(default=False, verbose_name='deceased')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='date of death')),
                ('has_allergies', models.BooleanField(default=False, verbose_name='has allergies')),
                ('allergy_notes', models.TextField(blank=True, verbose_name='allergy notes')),
                ('has_chronic_conditions', models.BooleanField(default=False, verbose_name='has chronic conditions')),
                ('chronic_conditions_notes', models.TextField(blank=True, verbose_name='chronic conditions notes')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10, verbose_name='blood type')),
                ('notes', models.TextField(blank=True, verbose_name='general notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='branches.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['mrn'], name='patients_pa_mrn_d0102f_idx'), models.Index(fields=['national_id'], name='patients_pa_nationa_70cc77_idx'), models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'), models.Index(fields=['branch', 'is_active'], name='patients_pa_branch__0a9a17_idx'), models.Index(fields=['date_of_birth'], name='patients_pa_date_of_4302f5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('branch', 'national_id'), name='unique_national_id_per_branch'),
        ),
    ]
